version: '3'
services:
  mysql:
    container_name: ppundo-mysql
    build:
      context: ./db
      dockerfile: exam.Dockerfile
    env_file: ./.env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "7152:3306"
    networks:
      - ppundo
  
  phpmyadmin:
    container_name: ppundo-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 7153:80
    env_file: ./.env
    depends_on:
      - mysql
    networks:
      - ppundo
  
  api:
    container_name: ppundo-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./api/:/app
    ports:
      - 7151:8080
    depends_on:
      - mysql
    networks:
      - ppundo

  client:
    container_name: ppundo-client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 7150:5173
    networks:
      - ppundo

volumes:
  mysql:

networks:
  ppundo:
    driver: bridge